name: Plugin Support
description: Requests regarding a specific plugin
title: "Plugin Support: "
labels: ["plugin support"]
body:
  - type: input
    id: plugin-name
    attributes:
      label: Plugin
      description: For which plugin is this issue?
      placeholder: "dataview"
    validations:
      required: true
  - type: textarea
    id: feature-requested
    attributes:
      label: Issue
      description: A clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To reproduce
      description: Step-by-step Instructions how someone not using the plugin would be able to reproduce the issue.
      placeholder: |
        1. Install the plugin
        2. Run the Command xyz.
        3. …
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain the issue.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
          required: true
        - label: My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)
          required: true
