name: Fix for existing problem
description: Submit a fix for an existing problem.
title: "Fix: "
labels: ["fix"]
body:
  - type: input
    id: issue-link
    attributes:
      label: Issue Link
      description: Add a link to the issue you are fixing.
    validations:
      required: true
  - type: textarea
    id: css-snippet
    attributes:
      label: CSS snippet
      description: code that will fix the issue
      render: CSS
    validations:
      required: true
